// <auto-generated />
using System;
using ContentManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContentManagement.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20210129100958_UnderPageTablesAdded")]
    partial class UnderPageTablesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ContentManagement.Models.Account.Users", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLoggedIn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UserCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UserEdited")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.HeaderModels.StartPage_HeaderMenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("StartPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartPageId");

                    b.ToTable("StartPage_HeaderMenus");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.HeaderModels.StartPage_HeaderTitels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime");

                    b.Property<int?>("HeaderMenuId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeaderMenuId");

                    b.HasIndex("UsersId");

                    b.ToTable("StartPage_HeaderTitels");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.PageModel.StartPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StartPages");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.PageModel.StartPage_ImgContents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("text");

                    b.Property<int?>("StartPageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Uploaded")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartPageId");

                    b.HasIndex("UserId");

                    b.ToTable("StartPage_ImgContents");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.PageModel.StartPage_TextContents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime");

                    b.Property<int?>("StartPageId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartPageId");

                    b.HasIndex("UserId");

                    b.ToTable("StartPage_TextContents");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.PageModel.StartPage_TitleContents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime");

                    b.Property<int?>("StartPageId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartPageId");

                    b.HasIndex("UserId");

                    b.ToTable("StartPage_TitleContents");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.HeaderModels.UnderPage_HeaderMenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("UnderPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnderPageId");

                    b.ToTable("UnderPage_HeaderMenus");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.HeaderModels.UnderPage_HeaderTitels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime");

                    b.Property<int?>("HeaderMenuId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeaderMenuId");

                    b.ToTable("UnderPage_HeaderTitels");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.PageModel.UnderPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnderPages");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.PageModel.UnderPage_ImgContents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("text");

                    b.Property<int?>("UnderPageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Uploaded")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("UnderPageId");

                    b.ToTable("UnderPages_imgcontents");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.PageModel.UnderPage_TextContents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<int?>("UnderPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnderPageId");

                    b.ToTable("UnderPages_TextContents");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.PageModel.UnderPage_TitleContents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<int?>("UnderPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnderPageId");

                    b.ToTable("UnderPages_titlecontents");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.HeaderModels.StartPage_HeaderMenus", b =>
                {
                    b.HasOne("ContentManagement.StartPageModels.PageModel.StartPage", "StartPage")
                        .WithMany()
                        .HasForeignKey("StartPageId");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.HeaderModels.StartPage_HeaderTitels", b =>
                {
                    b.HasOne("ContentManagement.StartPageModels.HeaderModels.StartPage_HeaderMenus", "HeaderMenu")
                        .WithMany("HeaderTitles")
                        .HasForeignKey("HeaderMenuId");

                    b.HasOne("ContentManagement.Models.Account.Users", null)
                        .WithMany("HeaderTitles")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.PageModel.StartPage_ImgContents", b =>
                {
                    b.HasOne("ContentManagement.StartPageModels.PageModel.StartPage", "StartPage")
                        .WithMany("StartPage_ImgContents")
                        .HasForeignKey("StartPageId");

                    b.HasOne("ContentManagement.Models.Account.Users", "User")
                        .WithMany("StartPage_ImgContents")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.PageModel.StartPage_TextContents", b =>
                {
                    b.HasOne("ContentManagement.StartPageModels.PageModel.StartPage", "StartPage")
                        .WithMany("StartPage_TextContents")
                        .HasForeignKey("StartPageId");

                    b.HasOne("ContentManagement.Models.Account.Users", "User")
                        .WithMany("StartPage_TextContents")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ContentManagement.StartPageModels.PageModel.StartPage_TitleContents", b =>
                {
                    b.HasOne("ContentManagement.StartPageModels.PageModel.StartPage", "StartPage")
                        .WithMany("StartPage_TitleContents")
                        .HasForeignKey("StartPageId");

                    b.HasOne("ContentManagement.Models.Account.Users", "User")
                        .WithMany("StartPage_Titles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.HeaderModels.UnderPage_HeaderMenus", b =>
                {
                    b.HasOne("ContentManagement.UnderPageModels.PageModel.UnderPage", "UnderPage")
                        .WithMany()
                        .HasForeignKey("UnderPageId");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.HeaderModels.UnderPage_HeaderTitels", b =>
                {
                    b.HasOne("ContentManagement.UnderPageModels.HeaderModels.UnderPage_HeaderMenus", "HeaderMenu")
                        .WithMany("HeaderTitles")
                        .HasForeignKey("HeaderMenuId");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.PageModel.UnderPage_ImgContents", b =>
                {
                    b.HasOne("ContentManagement.UnderPageModels.PageModel.UnderPage", "UnderPage")
                        .WithMany("UnderPage_ImgContents")
                        .HasForeignKey("UnderPageId");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.PageModel.UnderPage_TextContents", b =>
                {
                    b.HasOne("ContentManagement.UnderPageModels.PageModel.UnderPage", "UnderPage")
                        .WithMany("UnderPage_TextContents")
                        .HasForeignKey("UnderPageId");
                });

            modelBuilder.Entity("ContentManagement.UnderPageModels.PageModel.UnderPage_TitleContents", b =>
                {
                    b.HasOne("ContentManagement.UnderPageModels.PageModel.UnderPage", "UnderPage")
                        .WithMany("UnderPage_TitleContents")
                        .HasForeignKey("UnderPageId");
                });
#pragma warning restore 612, 618
        }
    }
}
